services:
  - type: web
    name: samen-api
    region: frankfurt
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 16.13.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /opt/render/project/src/data/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
